---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Profilarr"
  org.opencontainers.image.description: >
    Configuration management tool for Radarr/Sonarr that
    automates importing and version control of custom formats
    and quality profiles
  org.opencontainers.image.source: >
    https://github.com/123marvin123/homeassistant-addons
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  PROFILARR_VERSION: "v1.0.1"
